# Generated by Django 4.2.6 on 2023-10-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatars/profile.svg', upload_to='images/avatars/'),
        ),
    ]
