# Generated by Django 4.2.6 on 2023-10-19 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='url')),
                ('description', models.TextField(verbose_name='Описание рецепта')),
                ('cooking_steps', models.TextField(verbose_name='Инструкция')),
                ('ingredient', models.TextField(verbose_name='Ингредиенты ')),
                ('cooking_time', models.PositiveSmallIntegerField(verbose_name='Время приготовления (мин.)')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Опубликован')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('author', models.ManyToManyField(blank=True, related_name='receipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipes', to='receips.category', verbose_name='Категория')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='receips_rec_created_94b620_idx')],
            },
        ),
    ]
