# Generated by Django 4.2.6 on 2023-10-19 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_alter_tag_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='user_likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='author',
        ),
        migrations.AlterField(
            model_name='receipe',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipes', to='receips.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Список', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='receipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
