# Generated by Django 4.2.6 on 2023-10-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receips', '0002_receipe_user_likes_remove_receipe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipes', to='receips.category', verbose_name='Категория'),
        ),
    ]
