# Generated by Django 4.2.6 on 2023-10-20 14:51

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_alter_tag_slug'),
        ('receips', '0004_alter_receipe_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Список', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
