# Generated by Django 4.2.6 on 2023-10-20 14:54

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_alter_tag_slug'),
        ('receips', '0005_alter_receipe_image_alter_receipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Список тегов', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
