# Generated by Django 4.2.6 on 2023-10-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receips', '0006_alter_receipe_slug_alter_receipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='url'),
        ),
    ]
