# Generated by Django 4.2.6 on 2023-10-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receips', '0007_alter_receipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/category/', verbose_name='Изображение категории'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='servings',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество порций'),
        ),
    ]
