# Generated by Django 4.2.6 on 2023-10-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receips', '0008_category_image_receipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='servings',
            field=models.PositiveSmallIntegerField(verbose_name='Количество порций'),
        ),
    ]
